### PR TITLE
Fix azure update entrypoint.sh

### PR DESCRIPTION
**Pull request by antoinevokleber**
fix script shell in condition if

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @antoinevokleber,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by yuchaoran2011 — APPROVED** [review]

**Comment by yuchaoran2011** [comment]
@antoinevokleber Please sign the CLA and then I'll merge.

**Comment by antoinevokleber** [comment]
CLA signed

**Comment by yuchaoran2011** [comment]
@JustinPihony The contributor said he has signed the CLA but Github shows he hasn't. Could you take a look at it? Thanks!

**Comment by antoinevokleber** [comment]
i have send by email the CLA. Is the problem still there? I've requested Github support.

**Comment by JustinPihony** [comment]
Sorry about the delay - I reran the hook and all is green now :) @yuchaoran2011

**Comment by yuchaoran2011** [comment]
Thanks @JustinPihony!

**Pull request merged**
